export const MIN_PRESSURE_RELIEF_DURATION_SEC = 30;
export const MAX_PRESSURE_RELIEF_DURATION_SEC = 300;
export const PRESSURE_RELIEF_DURATION_STEP = 30;

export const MIN_PRESSURE_RELIEF_INTERVAL_MIN = 15;
export const MAX_PRESSURE_RELIEF_INTERVAL_MIN = 120;
export const PRESSURE_RELIEF_INTERVAL_STEP = 5;
